resilience4j:
  retry:
    instances:
      inventoryRetry:
        maxAttempts: 2
        waitDuration : 5s

  ratelimiter:
    instances :
      inventoryRateLimiter:
        limitForPeroid: 5
        limitRefreshperoid: 10s
        timeOutDuration: 2s


  circuitbreaker:
    instances:
      inventoryCircketBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

management:
  endpoints:
    web:
      exposure:
        include: "*"

  tracing:
    sampling:
      probability: 1.0


spring:
  zipkin:
    baseUrl: http://localhost:9411





