spring.application.name=order-service


server.servlet.context-path=/orders
server.port=9020

spring.datasource.url=jdbc:postgresql://localhost:5432/orderDB
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create-drop


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#eureka config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Force Eureka to use localhost instead of Windows hostname
eureka.instance.hostname=localhost

# Prefer using IP instead of Prakash.mshome.net
eureka.instance.prefer-ip-address=true

# Force Eureka to show instance as localhost:9010
eureka.instance.instance-id=${spring.application.name}:${server.port}

