spring:
  application:
    name: api-gateway

  zipkin:
    baseUrl: http://localhost:9411

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
            - name : LoggingOrdersFilter
            - name : AuthenticationFilter

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




jwt:
  secretKey: jaskdhvkasjcvhkzfhckbvafjszvoplasfdgkjhsdkjfhlawksdhfjkhwakdsjfkjwdshkzjfhkjsdhzkjvhdskjhfkjvwdskjzxbh


management:
  endpoints:
    web:
      exposure:
        include: "*"

  tracing:
    sampling:
      probability: 1.0


